--
-- PostgreSQL database dump
--

\restrict xxAghGk2FBhcFKvCb0EWZy3EBfZKXXPF2t42huV9hN5WHCUV3YYtgRXGgqTgXfm

-- Dumped from database version 16.14 (Debian 16.14-1.pgdg13+1)
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: common; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA common;


--
-- Name: SCHEMA common; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA common IS '공통 SSOT: tenants/domains/users/memberships + calls/call_transcript(ICS 콜 통합 적재본, QA·TA 공용). 서비스는 참조만(재정의 금지). 튜터는 콜 테이블 참조 안 함.';


--
-- Name: trustguard; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA trustguard;


--
-- Name: SCHEMA trustguard; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA trustguard IS 'QA(04) 고유표 — 신 스키마(50→30). 격리키=tenant_id(=common.tenants). 콜 헤더·발화는 common.calls/common.call_transcript 로 통합, qa_calls=평가레코드(call_id→common.calls). 전역기본=__default__.';


--
-- Name: logineventtype; Type: TYPE; Schema: common; Owner: -
--

CREATE TYPE common.logineventtype AS ENUM (
    'login_success',
    'otp_sent',
    'otp_verified',
    'otp_fail',
    'otp_expired',
    'logout',
    'session_revoked',
    'brand_switch',
    'login_fail'
);


--
-- Name: userrole; Type: TYPE; Schema: common; Owner: -
--

CREATE TYPE common.userrole AS ENUM (
    'agent',
    'admin',
    'super_admin'
);


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_sessions; Type: TABLE; Schema: common; Owner: -
--

CREATE TABLE common.auth_sessions (
    session_id character varying(36) NOT NULL,
    membership_id integer NOT NULL,
    issued_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    last_seen_at timestamp with time zone DEFAULT now() NOT NULL,
    revoked boolean DEFAULT false NOT NULL
);


--
-- Name: call_transcript; Type: TABLE; Schema: common; Owner: -
--

CREATE TABLE common.call_transcript (
    call_id bigint NOT NULL,
    seq integer NOT NULL,
    channel text DEFAULT 'call'::text NOT NULL,
    speaker text NOT NULL,
    text text NOT NULL,
    masking_data text,
    spoken_at timestamp with time zone,
    ta_skipped boolean DEFAULT false NOT NULL,
    ta_skip_reason text,
    agent_reply_at_1 timestamp with time zone,
    agent_reply_at_2 timestamp with time zone,
    CONSTRAINT call_transcript_channel_chk CHECK ((channel = ANY (ARRAY['call'::text, 'chat'::text, 'board'::text]))),
    CONSTRAINT call_transcript_speaker_chk CHECK ((speaker = ANY (ARRAY['agent'::text, 'customer'::text])))
);


--
-- Name: TABLE call_transcript; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON TABLE common.call_transcript IS 'ICS 콜 발화 통합 적재본(대화). 단일 테이블·channel(TYPE) 구분·원문+마스킹·speaker agent/customer.';


--
-- Name: calls; Type: TABLE; Schema: common; Owner: -
--

CREATE TABLE common.calls (
    call_id bigint NOT NULL,
    tenant_id public.citext NOT NULL,
    uid text NOT NULL,
    channel text DEFAULT 'call'::text NOT NULL,
    io_divi text,
    call_seq text,
    site_cd text,
    brand text,
    agent_code text,
    agent_user_id integer,
    customer_name text,
    status text,
    cdate timestamp with time zone,
    call_start_date timestamp with time zone,
    call_end_date timestamp with time zone,
    duration_sec integer,
    responded boolean,
    answered_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    source_id text,
    CONSTRAINT calls_channel_chk CHECK ((channel = ANY (ARRAY['call'::text, 'chat'::text, 'board'::text])))
);


--
-- Name: TABLE calls; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON TABLE common.calls IS 'ICS 콜 데이터 통합 적재본(헤더). QA·TA 공용. call_id PK + UNIQUE(tenant_id,uid). ICS 원천이 아니라 가져온 사본.';


--
-- Name: calls_call_id_seq; Type: SEQUENCE; Schema: common; Owner: -
--

ALTER TABLE common.calls ALTER COLUMN call_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME common.calls_call_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: domains; Type: TABLE; Schema: common; Owner: -
--

CREATE TABLE common.domains (
    id integer NOT NULL,
    name text NOT NULL,
    key text DEFAULT ''::text NOT NULL,
    parent_id integer,
    sort_order integer DEFAULT 0 NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: COLUMN domains.parent_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.domains.parent_id IS 'NULL=대분류(업종). 값 있으면 중분류(상위 대분류 id).';


--
-- Name: domains_id_seq; Type: SEQUENCE; Schema: common; Owner: -
--

CREATE SEQUENCE common.domains_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: domains_id_seq; Type: SEQUENCE OWNED BY; Schema: common; Owner: -
--

ALTER SEQUENCE common.domains_id_seq OWNED BY common.domains.id;


--
-- Name: login_history; Type: TABLE; Schema: common; Owner: -
--

CREATE TABLE common.login_history (
    id bigint NOT NULL,
    user_id integer,
    membership_id integer,
    email text,
    name text,
    event common.logineventtype NOT NULL,
    ip_address text,
    user_agent text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: login_history_id_seq; Type: SEQUENCE; Schema: common; Owner: -
--

CREATE SEQUENCE common.login_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: login_history_id_seq; Type: SEQUENCE OWNED BY; Schema: common; Owner: -
--

ALTER SEQUENCE common.login_history_id_seq OWNED BY common.login_history.id;


--
-- Name: memberships; Type: TABLE; Schema: common; Owner: -
--

CREATE TABLE common.memberships (
    id integer NOT NULL,
    user_id integer NOT NULL,
    tenant_id public.citext NOT NULL,
    role common.userrole DEFAULT 'agent'::common.userrole NOT NULL,
    department text,
    hire_date character varying(10),
    status character varying(16) DEFAULT 'active'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    leave_date character varying(10),
    extension character varying(32),
    dup_login_yn character varying(1) DEFAULT 'N'::character varying NOT NULL
);


--
-- Name: TABLE memberships; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON TABLE common.memberships IS 'user↔tenant 소속·권한. super_admin=크로스테넌트 관리(앱 로직).';


--
-- Name: memberships_id_seq; Type: SEQUENCE; Schema: common; Owner: -
--

CREATE SEQUENCE common.memberships_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: memberships_id_seq; Type: SEQUENCE OWNED BY; Schema: common; Owner: -
--

ALTER SEQUENCE common.memberships_id_seq OWNED BY common.memberships.id;


--
-- Name: tenants; Type: TABLE; Schema: common; Owner: -
--

CREATE TABLE common.tenants (
    tenant_id public.citext NOT NULL,
    name text NOT NULL,
    short text DEFAULT ''::text NOT NULL,
    color text DEFAULT '#055AAF'::text NOT NULL,
    domain_id integer,
    industry text,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE tenants; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON TABLE common.tenants IS '고객사 단위. tenant_id 값 == ICS proj_cd(1:1). 서비스 고유표는 tenant_id 를 FK 참조.';


--
-- Name: COLUMN tenants.tenant_id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.tenants.tenant_id IS 'ICS proj_cd 와 동일 값(citext, 소문자 canonical). 매핑 테이블 불필요.';


--
-- Name: users; Type: TABLE; Schema: common; Owner: -
--

CREATE TABLE common.users (
    id integer NOT NULL,
    email public.citext NOT NULL,
    name text NOT NULL,
    username public.citext,
    password_hash text,
    last_login_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    email_hash text NOT NULL,
    last_active_membership_id integer
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: common; Owner: -
--

CREATE SEQUENCE common.users_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: common; Owner: -
--

ALTER SEQUENCE common.users_id_seq OWNED BY common.users.id;


--
-- Name: coaching_assignment_reasons; Type: TABLE; Schema: trustguard; Owner: -
--

CREATE TABLE trustguard.coaching_assignment_reasons (
    id bigint NOT NULL,
    assignment_id bigint NOT NULL,
    member_user_id integer NOT NULL,
    qa_call_id bigint NOT NULL,
    note text,
    call_date text,
    score numeric,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: coaching_assignment_reasons_id_seq; Type: SEQUENCE; Schema: trustguard; Owner: -
--

ALTER TABLE trustguard.coaching_assignment_reasons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME trustguard.coaching_assignment_reasons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: coaching_assignments; Type: TABLE; Schema: trustguard; Owner: -
--

CREATE TABLE trustguard.coaching_assignments (
    id bigint NOT NULL,
    tenant_id public.citext,
    title text NOT NULL,
    target_type text DEFAULT 'group'::text NOT NULL,
    members integer[] DEFAULT '{}'::integer[] NOT NULL,
    action_items text[] DEFAULT '{}'::text[] NOT NULL,
    scenario_codes text[] DEFAULT '{}'::text[] NOT NULL,
    channel text DEFAULT 'call'::text NOT NULL,
    assigned_by_user_id integer,
    assigned_at timestamp with time zone DEFAULT now() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    archived_at timestamp with time zone,
    member_archived integer[] DEFAULT '{}'::integer[] NOT NULL
);


--
-- Name: coaching_assignments_id_seq; Type: SEQUENCE; Schema: trustguard; Owner: -
--

ALTER TABLE trustguard.coaching_assignments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME trustguard.coaching_assignments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: domain_default_eval_items; Type: TABLE; Schema: trustguard; Owner: -
--

CREATE TABLE trustguard.domain_default_eval_items (
    id integer NOT NULL,
    domain_id integer NOT NULL,
    order_no integer NOT NULL,
    category text NOT NULL,
    item text NOT NULL,
    criterion text,
    prompt_template text,
    pentagon_axis text,
    scoring_type text DEFAULT 'numeric'::text NOT NULL,
    max_score integer,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT domain_default_eval_items_scoring_type_chk CHECK ((scoring_type = ANY (ARRAY['numeric'::text, 'yes_no'::text])))
);


--
-- Name: domain_default_eval_items_id_seq; Type: SEQUENCE; Schema: trustguard; Owner: -
--

ALTER TABLE trustguard.domain_default_eval_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME trustguard.domain_default_eval_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: domain_default_pentagon_axes; Type: TABLE; Schema: trustguard; Owner: -
--

CREATE TABLE trustguard.domain_default_pentagon_axes (
    id integer NOT NULL,
    domain_id integer NOT NULL,
    axis_no integer NOT NULL,
    label text NOT NULL,
    description text,
    prompt_template text,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: domain_default_pentagon_axes_id_seq; Type: SEQUENCE; Schema: trustguard; Owner: -
--

ALTER TABLE trustguard.domain_default_pentagon_axes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME trustguard.domain_default_pentagon_axes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: eval_annotation; Type: TABLE; Schema: trustguard; Owner: -
--

CREATE TABLE trustguard.eval_annotation (
    call_id bigint NOT NULL,
    comments jsonb DEFAULT '[]'::jsonb NOT NULL,
    comments_at timestamp with time zone,
    judgments jsonb,
    has_uncertain boolean,
    has_weak boolean,
    has_contradiction boolean,
    prompt_version integer,
    model text,
    judged_at timestamp with time zone
);


--
-- Name: eval_emotion_recovery; Type: TABLE; Schema: trustguard; Owner: -
--

CREATE TABLE trustguard.eval_emotion_recovery (
    call_id bigint NOT NULL,
    segment_count integer DEFAULT 0 NOT NULL,
    neg_seg_count integer DEFAULT 0 NOT NULL,
    first_neg_idx integer,
    final_sentiment text,
    had_negative boolean DEFAULT false NOT NULL,
    recovered boolean DEFAULT false NOT NULL,
    source text DEFAULT 'ta_segments'::text NOT NULL,
    analyzed_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: eval_item_defs; Type: TABLE; Schema: trustguard; Owner: -
--

CREATE TABLE trustguard.eval_item_defs (
    id integer NOT NULL,
    tenant_id public.citext NOT NULL,
    order_no integer NOT NULL,
    category text NOT NULL,
    item text NOT NULL,
    criterion text,
    prompt_template text,
    department text DEFAULT '기본'::text NOT NULL,
    version integer DEFAULT 1 NOT NULL,
    effective_from timestamp with time zone DEFAULT now() NOT NULL,
    deactivated_at timestamp with time zone,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    pentagon_axis text,
    scoring_type text DEFAULT 'numeric'::text NOT NULL,
    max_score integer,
    is_active boolean DEFAULT true NOT NULL,
    CONSTRAINT eval_item_defs_scoring_type_chk CHECK ((scoring_type = ANY (ARRAY['numeric'::text, 'yes_no'::text])))
);


--
-- Name: eval_item_defs_id_seq; Type: SEQUENCE; Schema: trustguard; Owner: -
--

ALTER TABLE trustguard.eval_item_defs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME trustguard.eval_item_defs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: eval_item_score; Type: TABLE; Schema: trustguard; Owner: -
--

CREATE TABLE trustguard.eval_item_score (
    call_id bigint NOT NULL,
    order_no integer NOT NULL,
    category text NOT NULL,
    item text NOT NULL,
    reason_text text NOT NULL,
    ai_eval double precision NOT NULL,
    manual_eval double precision NOT NULL,
    agent_utterance text,
    max_score numeric,
    manual_eval_option text,
    counselor_eval double precision,
    skill_excluded_at timestamp with time zone
);


--
-- Name: eval_ksqi_score; Type: TABLE; Schema: trustguard; Owner: -
--

CREATE TABLE trustguard.eval_ksqi_score (
    call_id bigint NOT NULL,
    item_number integer NOT NULL,
    item_name text DEFAULT ''::text NOT NULL,
    area text DEFAULT ''::text NOT NULL,
    kind text DEFAULT 'llm'::text NOT NULL,
    score double precision,
    max_score double precision,
    na boolean DEFAULT false NOT NULL,
    defect boolean DEFAULT false NOT NULL,
    rationale text DEFAULT ''::text NOT NULL,
    evidence jsonb DEFAULT '[]'::jsonb NOT NULL
);


--
-- Name: eval_ksqi_summary; Type: TABLE; Schema: trustguard; Owner: -
--

CREATE TABLE trustguard.eval_ksqi_summary (
    call_id bigint NOT NULL,
    area_a_raw double precision,
    area_a_max double precision,
    area_a_scaled double precision,
    area_a_grade text,
    area_a_excellent boolean,
    area_b_raw double precision,
    area_b_max double precision,
    area_b_scaled double precision,
    area_b_grade text,
    area_b_excellent boolean,
    overall_raw double precision,
    overall_max double precision,
    summary text DEFAULT ''::text NOT NULL
);


--
-- Name: eval_pentagon_result; Type: TABLE; Schema: trustguard; Owner: -
--

CREATE TABLE trustguard.eval_pentagon_result (
    call_id bigint NOT NULL,
    item_type_no integer NOT NULL,
    item_type text NOT NULL,
    rating text,
    comment text NOT NULL,
    summary text
);


--
-- Name: eval_review_event; Type: TABLE; Schema: trustguard; Owner: -
--

CREATE TABLE trustguard.eval_review_event (
    id bigint NOT NULL,
    call_id bigint NOT NULL,
    round integer DEFAULT 0 NOT NULL,
    actor_user_id integer,
    action text NOT NULL,
    changed_items jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    reason text
);


--
-- Name: ics_qa_poll_watermark; Type: TABLE; Schema: trustguard; Owner: -
--

CREATE TABLE trustguard.ics_qa_poll_watermark (
    tenant_id public.citext NOT NULL,
    last_call_end_date timestamp with time zone,
    last_uid text,
    processed_count bigint DEFAULT 0 NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: ksqi_item_defs; Type: TABLE; Schema: trustguard; Owner: -
--

CREATE TABLE trustguard.ksqi_item_defs (
    id integer NOT NULL,
    tenant_id public.citext NOT NULL,
    number integer NOT NULL,
    name text NOT NULL,
    area text NOT NULL,
    category text DEFAULT ''::text NOT NULL,
    kind text DEFAULT 'llm'::text NOT NULL,
    max_score integer DEFAULT 10 NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: ksqi_item_defs_id_seq; Type: SEQUENCE; Schema: trustguard; Owner: -
--

ALTER TABLE trustguard.ksqi_item_defs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME trustguard.ksqi_item_defs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification_prefs; Type: TABLE; Schema: trustguard; Owner: -
--

CREATE TABLE trustguard.notification_prefs (
    user_id integer NOT NULL,
    prefs jsonb DEFAULT '{}'::jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: notifications; Type: TABLE; Schema: trustguard; Owner: -
--

CREATE TABLE trustguard.notifications (
    id bigint NOT NULL,
    recipient_user_id integer NOT NULL,
    type text NOT NULL,
    title text NOT NULL,
    body text,
    resource_type text,
    resource_id text,
    actor_user_id integer,
    actor_name text,
    tenant_id public.citext,
    read_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: trustguard; Owner: -
--

ALTER TABLE trustguard.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME trustguard.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pentagon_axes; Type: TABLE; Schema: trustguard; Owner: -
--

CREATE TABLE trustguard.pentagon_axes (
    id integer NOT NULL,
    tenant_id public.citext NOT NULL,
    department text DEFAULT '기본'::text NOT NULL,
    axis_no integer NOT NULL,
    label text NOT NULL,
    description text,
    prompt_template text,
    is_active boolean DEFAULT true NOT NULL,
    version integer DEFAULT 1 NOT NULL,
    effective_from timestamp with time zone DEFAULT now() NOT NULL,
    deactivated_at timestamp with time zone,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: pentagon_axes_id_seq; Type: SEQUENCE; Schema: trustguard; Owner: -
--

ALTER TABLE trustguard.pentagon_axes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME trustguard.pentagon_axes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: qa_audit_logs; Type: TABLE; Schema: trustguard; Owner: -
--

CREATE TABLE trustguard.qa_audit_logs (
    audit_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id integer,
    login_id text NOT NULL,
    display_name text,
    role text,
    action text NOT NULL,
    resource_type text NOT NULL,
    resource_id text NOT NULL,
    http_method text,
    http_path text,
    client_ip text,
    user_agent text,
    detail_json text,
    success smallint DEFAULT 1 NOT NULL,
    error_message text
);


--
-- Name: qa_audit_logs_audit_id_seq; Type: SEQUENCE; Schema: trustguard; Owner: -
--

ALTER TABLE trustguard.qa_audit_logs ALTER COLUMN audit_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME trustguard.qa_audit_logs_audit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: qa_batch_configs; Type: TABLE; Schema: trustguard; Owner: -
--

CREATE TABLE trustguard.qa_batch_configs (
    tenant_id public.citext NOT NULL,
    config jsonb DEFAULT '{}'::jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_by integer
);


--
-- Name: qa_call_review_event_id_seq; Type: SEQUENCE; Schema: trustguard; Owner: -
--

ALTER TABLE trustguard.eval_review_event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME trustguard.qa_call_review_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: qa_confidence_prompt; Type: TABLE; Schema: trustguard; Owner: -
--

CREATE TABLE trustguard.qa_confidence_prompt (
    id integer NOT NULL,
    tenant_id public.citext NOT NULL,
    version integer DEFAULT 1 NOT NULL,
    system_prompt text,
    uncertain_def text,
    contradiction_def text,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_by integer,
    updated_by_name text
);


--
-- Name: qa_confidence_prompt_id_seq; Type: SEQUENCE; Schema: trustguard; Owner: -
--

ALTER TABLE trustguard.qa_confidence_prompt ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME trustguard.qa_confidence_prompt_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: qa_evaluations; Type: TABLE; Schema: trustguard; Owner: -
--

CREATE TABLE trustguard.qa_evaluations (
    call_id bigint NOT NULL,
    "AI_SCORE" double precision NOT NULL,
    "TOTAL_SCORE" double precision NOT NULL,
    department text DEFAULT '컬렉션관리부'::text NOT NULL,
    role text DEFAULT 'PDS1'::text NOT NULL,
    ai_analysis_target text,
    ai_analysis_reason text,
    is_sandbox boolean DEFAULT false NOT NULL,
    review_status text DEFAULT 'pending'::text NOT NULL,
    review_started_at timestamp with time zone,
    review_completed_at timestamp with time zone,
    user_id integer,
    approved_at timestamp with time zone,
    approved_by_user_id integer,
    review_round integer DEFAULT 0 NOT NULL,
    manual_review boolean DEFAULT false NOT NULL,
    manual_review_reasons jsonb DEFAULT '[]'::jsonb NOT NULL,
    manual_review_at timestamp with time zone,
    CONSTRAINT qa_calls_ai_target_chk CHECK (((ai_analysis_target IS NULL) OR (ai_analysis_target = ANY (ARRAY['O'::text, 'X'::text])))),
    CONSTRAINT qa_calls_department_chk CHECK ((department = ANY (ARRAY['컬렉션관리부'::text, '소비자보호부'::text, '고객센터'::text, '고객지원실'::text]))),
    CONSTRAINT qa_calls_review_status_chk CHECK ((review_status = ANY (ARRAY['pending'::text, 'in_review'::text, 'review_done'::text, 'admin_revised'::text, 'objection'::text, 'approved'::text, 'completed'::text]))),
    CONSTRAINT qa_calls_role_chk CHECK ((role = ANY (ARRAY['PDS1'::text, 'PDS2'::text, 'PDS3'::text, '수동대인'::text, '인바운드'::text, '전체'::text])))
);


--
-- Name: qa_golden_set; Type: TABLE; Schema: trustguard; Owner: -
--

CREATE TABLE trustguard.qa_golden_set (
    golden_id integer NOT NULL,
    qa_id bigint NOT NULL,
    order_no integer NOT NULL,
    tenant_id public.citext,
    category text NOT NULL,
    item text NOT NULL,
    reason_text text,
    agent_utterance text,
    score double precision NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: qa_golden_set_golden_id_seq; Type: SEQUENCE; Schema: trustguard; Owner: -
--

ALTER TABLE trustguard.qa_golden_set ALTER COLUMN golden_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME trustguard.qa_golden_set_golden_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: qa_skill_store; Type: TABLE; Schema: trustguard; Owner: -
--

CREATE TABLE trustguard.qa_skill_store (
    rubric_id text NOT NULL,
    tenant_id public.citext,
    memory jsonb DEFAULT '{}'::jsonb NOT NULL,
    store jsonb DEFAULT '{}'::jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: rubric_change_log; Type: TABLE; Schema: trustguard; Owner: -
--

CREATE TABLE trustguard.rubric_change_log (
    id integer NOT NULL,
    tenant_id public.citext NOT NULL,
    target_kind text NOT NULL,
    department text DEFAULT '기본'::text NOT NULL,
    target_no integer,
    target_name text,
    category_name text,
    version integer,
    change_type text NOT NULL,
    before_json jsonb,
    after_json jsonb,
    user_id integer,
    login_id text,
    display_name text,
    changed_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: rubric_change_log_id_seq; Type: SEQUENCE; Schema: trustguard; Owner: -
--

ALTER TABLE trustguard.rubric_change_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME trustguard.rubric_change_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tenant_rag_config; Type: TABLE; Schema: trustguard; Owner: -
--

CREATE TABLE trustguard.tenant_rag_config (
    tenant_id public.citext NOT NULL,
    rubric_id text DEFAULT ''::text NOT NULL,
    item_names jsonb DEFAULT '[]'::jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE tenant_rag_config; Type: COMMENT; Schema: trustguard; Owner: -
--

COMMENT ON TABLE trustguard.tenant_rag_config IS 'QA 브랜드 RAG few-shot 설정(구 organizations.rag_rubric_id/rag_fewshot_item_names). tenant_id 단위. RAG는 기본 숨김/비활성.';


--
-- Name: domains id; Type: DEFAULT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.domains ALTER COLUMN id SET DEFAULT nextval('common.domains_id_seq'::regclass);


--
-- Name: login_history id; Type: DEFAULT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.login_history ALTER COLUMN id SET DEFAULT nextval('common.login_history_id_seq'::regclass);


--
-- Name: memberships id; Type: DEFAULT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.memberships ALTER COLUMN id SET DEFAULT nextval('common.memberships_id_seq'::regclass);


--
-- Name: users id; Type: DEFAULT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.users ALTER COLUMN id SET DEFAULT nextval('common.users_id_seq'::regclass);


--
-- Name: auth_sessions auth_sessions_pkey; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.auth_sessions
    ADD CONSTRAINT auth_sessions_pkey PRIMARY KEY (session_id);


--
-- Name: call_transcript call_transcript_pkey; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.call_transcript
    ADD CONSTRAINT call_transcript_pkey PRIMARY KEY (call_id, seq);


--
-- Name: calls calls_pkey; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.calls
    ADD CONSTRAINT calls_pkey PRIMARY KEY (call_id);


--
-- Name: calls calls_tenant_uid_uk; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.calls
    ADD CONSTRAINT calls_tenant_uid_uk UNIQUE (tenant_id, uid);


--
-- Name: domains domains_pkey; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.domains
    ADD CONSTRAINT domains_pkey PRIMARY KEY (id);


--
-- Name: login_history login_history_pkey; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.login_history
    ADD CONSTRAINT login_history_pkey PRIMARY KEY (id);


--
-- Name: memberships memberships_pkey; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.memberships
    ADD CONSTRAINT memberships_pkey PRIMARY KEY (id);


--
-- Name: memberships memberships_user_id_tenant_id_key; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.memberships
    ADD CONSTRAINT memberships_user_id_tenant_id_key UNIQUE (user_id, tenant_id);


--
-- Name: tenants tenants_pkey; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.tenants
    ADD CONSTRAINT tenants_pkey PRIMARY KEY (tenant_id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: coaching_assignment_reasons coaching_assignment_reasons_pkey; Type: CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.coaching_assignment_reasons
    ADD CONSTRAINT coaching_assignment_reasons_pkey PRIMARY KEY (id);


--
-- Name: coaching_assignment_reasons coaching_assignment_reasons_uk; Type: CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.coaching_assignment_reasons
    ADD CONSTRAINT coaching_assignment_reasons_uk UNIQUE (assignment_id, member_user_id, qa_call_id);


--
-- Name: coaching_assignments coaching_assignments_pkey; Type: CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.coaching_assignments
    ADD CONSTRAINT coaching_assignments_pkey PRIMARY KEY (id);


--
-- Name: domain_default_eval_items domain_default_eval_items_pkey; Type: CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.domain_default_eval_items
    ADD CONSTRAINT domain_default_eval_items_pkey PRIMARY KEY (id);


--
-- Name: domain_default_pentagon_axes domain_default_pentagon_axes_pkey; Type: CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.domain_default_pentagon_axes
    ADD CONSTRAINT domain_default_pentagon_axes_pkey PRIMARY KEY (id);


--
-- Name: eval_item_defs eval_item_defs_pkey; Type: CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.eval_item_defs
    ADD CONSTRAINT eval_item_defs_pkey PRIMARY KEY (id);


--
-- Name: eval_item_defs eval_item_defs_versioned_uk; Type: CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.eval_item_defs
    ADD CONSTRAINT eval_item_defs_versioned_uk UNIQUE (tenant_id, department, order_no, version);


--
-- Name: ics_qa_poll_watermark ics_qa_poll_watermark_pkey; Type: CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.ics_qa_poll_watermark
    ADD CONSTRAINT ics_qa_poll_watermark_pkey PRIMARY KEY (tenant_id);


--
-- Name: ksqi_item_defs ksqi_item_defs_org_number_uk; Type: CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.ksqi_item_defs
    ADD CONSTRAINT ksqi_item_defs_org_number_uk UNIQUE (tenant_id, number);


--
-- Name: ksqi_item_defs ksqi_item_defs_pkey; Type: CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.ksqi_item_defs
    ADD CONSTRAINT ksqi_item_defs_pkey PRIMARY KEY (id);


--
-- Name: notification_prefs notification_prefs_pkey; Type: CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.notification_prefs
    ADD CONSTRAINT notification_prefs_pkey PRIMARY KEY (user_id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: pentagon_axes pentagon_axes_pkey; Type: CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.pentagon_axes
    ADD CONSTRAINT pentagon_axes_pkey PRIMARY KEY (id);


--
-- Name: pentagon_axes pentagon_axes_versioned_uk; Type: CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.pentagon_axes
    ADD CONSTRAINT pentagon_axes_versioned_uk UNIQUE (tenant_id, department, axis_no, version);


--
-- Name: qa_audit_logs qa_audit_logs_pkey; Type: CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.qa_audit_logs
    ADD CONSTRAINT qa_audit_logs_pkey PRIMARY KEY (audit_id);


--
-- Name: qa_batch_configs qa_batch_configs_pkey; Type: CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.qa_batch_configs
    ADD CONSTRAINT qa_batch_configs_pkey PRIMARY KEY (tenant_id);


--
-- Name: eval_annotation qa_call_annotation_pkey; Type: CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.eval_annotation
    ADD CONSTRAINT qa_call_annotation_pkey PRIMARY KEY (call_id);


--
-- Name: eval_emotion_recovery qa_call_emotion_recovery_pkey; Type: CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.eval_emotion_recovery
    ADD CONSTRAINT qa_call_emotion_recovery_pkey PRIMARY KEY (call_id);


--
-- Name: eval_item_score qa_call_item_score_pkey; Type: CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.eval_item_score
    ADD CONSTRAINT qa_call_item_score_pkey PRIMARY KEY (call_id, order_no);


--
-- Name: eval_ksqi_score qa_call_ksqi_score_pkey; Type: CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.eval_ksqi_score
    ADD CONSTRAINT qa_call_ksqi_score_pkey PRIMARY KEY (call_id, item_number);


--
-- Name: eval_ksqi_summary qa_call_ksqi_summary_pkey; Type: CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.eval_ksqi_summary
    ADD CONSTRAINT qa_call_ksqi_summary_pkey PRIMARY KEY (call_id);


--
-- Name: eval_pentagon_result qa_call_pentagon_result_pkey; Type: CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.eval_pentagon_result
    ADD CONSTRAINT qa_call_pentagon_result_pkey PRIMARY KEY (call_id, item_type_no);


--
-- Name: eval_review_event qa_call_review_event_pkey; Type: CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.eval_review_event
    ADD CONSTRAINT qa_call_review_event_pkey PRIMARY KEY (id);


--
-- Name: qa_evaluations qa_calls_pkey; Type: CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.qa_evaluations
    ADD CONSTRAINT qa_calls_pkey PRIMARY KEY (call_id);


--
-- Name: qa_confidence_prompt qa_confidence_prompt_pkey; Type: CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.qa_confidence_prompt
    ADD CONSTRAINT qa_confidence_prompt_pkey PRIMARY KEY (id);


--
-- Name: qa_confidence_prompt qa_confidence_prompt_tenant_version_key; Type: CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.qa_confidence_prompt
    ADD CONSTRAINT qa_confidence_prompt_tenant_version_key UNIQUE (tenant_id, version);


--
-- Name: qa_golden_set qa_golden_set_call_order_uk; Type: CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.qa_golden_set
    ADD CONSTRAINT qa_golden_set_call_order_uk UNIQUE (qa_id, order_no);


--
-- Name: qa_golden_set qa_golden_set_pkey; Type: CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.qa_golden_set
    ADD CONSTRAINT qa_golden_set_pkey PRIMARY KEY (golden_id);


--
-- Name: qa_skill_store qa_skill_store_pkey; Type: CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.qa_skill_store
    ADD CONSTRAINT qa_skill_store_pkey PRIMARY KEY (rubric_id);


--
-- Name: rubric_change_log rubric_change_log_pkey; Type: CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.rubric_change_log
    ADD CONSTRAINT rubric_change_log_pkey PRIMARY KEY (id);


--
-- Name: tenant_rag_config tenant_rag_config_pkey; Type: CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.tenant_rag_config
    ADD CONSTRAINT tenant_rag_config_pkey PRIMARY KEY (tenant_id);


--
-- Name: idx_auth_sessions_membership; Type: INDEX; Schema: common; Owner: -
--

CREATE INDEX idx_auth_sessions_membership ON common.auth_sessions USING btree (membership_id);


--
-- Name: idx_calls_agent_code; Type: INDEX; Schema: common; Owner: -
--

CREATE INDEX idx_calls_agent_code ON common.calls USING btree (agent_code);


--
-- Name: idx_calls_agent_user; Type: INDEX; Schema: common; Owner: -
--

CREATE INDEX idx_calls_agent_user ON common.calls USING btree (agent_user_id);


--
-- Name: idx_calls_channel; Type: INDEX; Schema: common; Owner: -
--

CREATE INDEX idx_calls_channel ON common.calls USING btree (tenant_id, channel);


--
-- Name: idx_calls_source_id; Type: INDEX; Schema: common; Owner: -
--

CREATE UNIQUE INDEX idx_calls_source_id ON common.calls USING btree (tenant_id, source_id) WHERE (source_id IS NOT NULL);


--
-- Name: idx_calls_tenant; Type: INDEX; Schema: common; Owner: -
--

CREATE INDEX idx_calls_tenant ON common.calls USING btree (tenant_id);


--
-- Name: idx_calls_tenant_start; Type: INDEX; Schema: common; Owner: -
--

CREATE INDEX idx_calls_tenant_start ON common.calls USING btree (tenant_id, call_start_date DESC);


--
-- Name: idx_calls_uid; Type: INDEX; Schema: common; Owner: -
--

CREATE INDEX idx_calls_uid ON common.calls USING btree (uid);


--
-- Name: idx_domains_parent; Type: INDEX; Schema: common; Owner: -
--

CREATE INDEX idx_domains_parent ON common.domains USING btree (parent_id);


--
-- Name: idx_domains_sort; Type: INDEX; Schema: common; Owner: -
--

CREATE INDEX idx_domains_sort ON common.domains USING btree (sort_order, id);


--
-- Name: idx_login_history_membership; Type: INDEX; Schema: common; Owner: -
--

CREATE INDEX idx_login_history_membership ON common.login_history USING btree (membership_id);


--
-- Name: idx_login_history_user; Type: INDEX; Schema: common; Owner: -
--

CREATE INDEX idx_login_history_user ON common.login_history USING btree (user_id);


--
-- Name: idx_memberships_tenant; Type: INDEX; Schema: common; Owner: -
--

CREATE INDEX idx_memberships_tenant ON common.memberships USING btree (tenant_id);


--
-- Name: idx_memberships_user; Type: INDEX; Schema: common; Owner: -
--

CREATE INDEX idx_memberships_user ON common.memberships USING btree (user_id);


--
-- Name: idx_tenants_active; Type: INDEX; Schema: common; Owner: -
--

CREATE INDEX idx_tenants_active ON common.tenants USING btree (active);


--
-- Name: idx_tenants_domain; Type: INDEX; Schema: common; Owner: -
--

CREATE INDEX idx_tenants_domain ON common.tenants USING btree (domain_id);


--
-- Name: idx_transcript_channel; Type: INDEX; Schema: common; Owner: -
--

CREATE INDEX idx_transcript_channel ON common.call_transcript USING btree (call_id, channel);


--
-- Name: idx_users_email; Type: INDEX; Schema: common; Owner: -
--

CREATE INDEX idx_users_email ON common.users USING btree (email);


--
-- Name: uq_domains_key; Type: INDEX; Schema: common; Owner: -
--

CREATE UNIQUE INDEX uq_domains_key ON common.domains USING btree (key) WHERE (key <> ''::text);


--
-- Name: ux_users_email_hash; Type: INDEX; Schema: common; Owner: -
--

CREATE UNIQUE INDEX ux_users_email_hash ON common.users USING btree (email_hash);


--
-- Name: domain_default_eval_items_uk; Type: INDEX; Schema: trustguard; Owner: -
--

CREATE UNIQUE INDEX domain_default_eval_items_uk ON trustguard.domain_default_eval_items USING btree (domain_id, order_no);


--
-- Name: domain_default_pentagon_axes_uk; Type: INDEX; Schema: trustguard; Owner: -
--

CREATE UNIQUE INDEX domain_default_pentagon_axes_uk ON trustguard.domain_default_pentagon_axes USING btree (domain_id, axis_no);


--
-- Name: idx_coaching_assignments_members; Type: INDEX; Schema: trustguard; Owner: -
--

CREATE INDEX idx_coaching_assignments_members ON trustguard.coaching_assignments USING gin (members);


--
-- Name: idx_coaching_assignments_org; Type: INDEX; Schema: trustguard; Owner: -
--

CREATE INDEX idx_coaching_assignments_org ON trustguard.coaching_assignments USING btree (tenant_id);


--
-- Name: idx_coaching_reasons_assignment; Type: INDEX; Schema: trustguard; Owner: -
--

CREATE INDEX idx_coaching_reasons_assignment ON trustguard.coaching_assignment_reasons USING btree (assignment_id);


--
-- Name: idx_coaching_reasons_member; Type: INDEX; Schema: trustguard; Owner: -
--

CREATE INDEX idx_coaching_reasons_member ON trustguard.coaching_assignment_reasons USING btree (member_user_id);


--
-- Name: idx_eval_item_defs_active; Type: INDEX; Schema: trustguard; Owner: -
--

CREATE INDEX idx_eval_item_defs_active ON trustguard.eval_item_defs USING btree (tenant_id, department, order_no) WHERE ((deactivated_at IS NULL) AND (is_active = true));


--
-- Name: idx_eval_item_defs_effective; Type: INDEX; Schema: trustguard; Owner: -
--

CREATE INDEX idx_eval_item_defs_effective ON trustguard.eval_item_defs USING btree (tenant_id, department, effective_from DESC);


--
-- Name: idx_eval_item_defs_org; Type: INDEX; Schema: trustguard; Owner: -
--

CREATE INDEX idx_eval_item_defs_org ON trustguard.eval_item_defs USING btree (tenant_id, order_no);


--
-- Name: idx_notifications_recipient; Type: INDEX; Schema: trustguard; Owner: -
--

CREATE INDEX idx_notifications_recipient ON trustguard.notifications USING btree (recipient_user_id, created_at DESC);


--
-- Name: idx_notifications_unread; Type: INDEX; Schema: trustguard; Owner: -
--

CREATE INDEX idx_notifications_unread ON trustguard.notifications USING btree (recipient_user_id) WHERE (read_at IS NULL);


--
-- Name: idx_pentagon_axes_effective; Type: INDEX; Schema: trustguard; Owner: -
--

CREATE INDEX idx_pentagon_axes_effective ON trustguard.pentagon_axes USING btree (tenant_id, department, effective_from DESC);


--
-- Name: idx_pentagon_axes_org; Type: INDEX; Schema: trustguard; Owner: -
--

CREATE INDEX idx_pentagon_axes_org ON trustguard.pentagon_axes USING btree (tenant_id, axis_no);


--
-- Name: idx_qa_audit_action; Type: INDEX; Schema: trustguard; Owner: -
--

CREATE INDEX idx_qa_audit_action ON trustguard.qa_audit_logs USING btree (action, created_at DESC);


--
-- Name: idx_qa_audit_created; Type: INDEX; Schema: trustguard; Owner: -
--

CREATE INDEX idx_qa_audit_created ON trustguard.qa_audit_logs USING btree (created_at DESC);


--
-- Name: idx_qa_audit_resource; Type: INDEX; Schema: trustguard; Owner: -
--

CREATE INDEX idx_qa_audit_resource ON trustguard.qa_audit_logs USING btree (resource_type, resource_id);


--
-- Name: idx_qa_audit_user_time; Type: INDEX; Schema: trustguard; Owner: -
--

CREATE INDEX idx_qa_audit_user_time ON trustguard.qa_audit_logs USING btree (login_id, created_at DESC);


--
-- Name: idx_qa_call_annotation_flags; Type: INDEX; Schema: trustguard; Owner: -
--

CREATE INDEX idx_qa_call_annotation_flags ON trustguard.eval_annotation USING btree (call_id) WHERE (has_uncertain OR has_weak OR has_contradiction);


--
-- Name: idx_qa_call_item_score_scored; Type: INDEX; Schema: trustguard; Owner: -
--

CREATE INDEX idx_qa_call_item_score_scored ON trustguard.eval_item_score USING btree (call_id) WHERE (max_score IS NOT NULL);


--
-- Name: idx_qa_call_item_score_skill_excluded; Type: INDEX; Schema: trustguard; Owner: -
--

CREATE INDEX idx_qa_call_item_score_skill_excluded ON trustguard.eval_item_score USING btree (call_id, order_no) WHERE (skill_excluded_at IS NOT NULL);


--
-- Name: idx_qa_calls_is_sandbox; Type: INDEX; Schema: trustguard; Owner: -
--

CREATE INDEX idx_qa_calls_is_sandbox ON trustguard.qa_evaluations USING btree (is_sandbox) WHERE (is_sandbox = true);


--
-- Name: idx_qa_calls_manual_review; Type: INDEX; Schema: trustguard; Owner: -
--

CREATE INDEX idx_qa_calls_manual_review ON trustguard.qa_evaluations USING btree (manual_review) WHERE (manual_review = true);


--
-- Name: idx_qa_calls_review_status; Type: INDEX; Schema: trustguard; Owner: -
--

CREATE INDEX idx_qa_calls_review_status ON trustguard.qa_evaluations USING btree (review_status);


--
-- Name: idx_qa_confidence_prompt_current; Type: INDEX; Schema: trustguard; Owner: -
--

CREATE INDEX idx_qa_confidence_prompt_current ON trustguard.qa_confidence_prompt USING btree (tenant_id, version DESC);


--
-- Name: idx_qa_golden_set_created; Type: INDEX; Schema: trustguard; Owner: -
--

CREATE INDEX idx_qa_golden_set_created ON trustguard.qa_golden_set USING btree (created_at DESC);


--
-- Name: idx_qa_golden_set_lookup; Type: INDEX; Schema: trustguard; Owner: -
--

CREATE INDEX idx_qa_golden_set_lookup ON trustguard.qa_golden_set USING btree (tenant_id, category, item);


--
-- Name: idx_qa_review_events_qa; Type: INDEX; Schema: trustguard; Owner: -
--

CREATE INDEX idx_qa_review_events_qa ON trustguard.eval_review_event USING btree (call_id, created_at);


--
-- Name: idx_qa_skill_store_org; Type: INDEX; Schema: trustguard; Owner: -
--

CREATE INDEX idx_qa_skill_store_org ON trustguard.qa_skill_store USING btree (tenant_id);


--
-- Name: idx_rubric_change_log_lookup; Type: INDEX; Schema: trustguard; Owner: -
--

CREATE INDEX idx_rubric_change_log_lookup ON trustguard.rubric_change_log USING btree (tenant_id, target_kind, department, target_no, changed_at DESC);


--
-- Name: idx_rubric_change_log_org_time; Type: INDEX; Schema: trustguard; Owner: -
--

CREATE INDEX idx_rubric_change_log_org_time ON trustguard.rubric_change_log USING btree (tenant_id, changed_at DESC);


--
-- Name: ix_ksqi_item_defs_org; Type: INDEX; Schema: trustguard; Owner: -
--

CREATE INDEX ix_ksqi_item_defs_org ON trustguard.ksqi_item_defs USING btree (tenant_id);


--
-- Name: auth_sessions auth_sessions_membership_id_fkey; Type: FK CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.auth_sessions
    ADD CONSTRAINT auth_sessions_membership_id_fkey FOREIGN KEY (membership_id) REFERENCES common.memberships(id) ON DELETE CASCADE;


--
-- Name: call_transcript call_transcript_call_id_fkey; Type: FK CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.call_transcript
    ADD CONSTRAINT call_transcript_call_id_fkey FOREIGN KEY (call_id) REFERENCES common.calls(call_id) ON DELETE CASCADE;


--
-- Name: calls calls_agent_user_id_fkey; Type: FK CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.calls
    ADD CONSTRAINT calls_agent_user_id_fkey FOREIGN KEY (agent_user_id) REFERENCES common.users(id) ON DELETE SET NULL;


--
-- Name: calls calls_tenant_id_fkey; Type: FK CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.calls
    ADD CONSTRAINT calls_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES common.tenants(tenant_id) ON UPDATE CASCADE;


--
-- Name: domains domains_parent_id_fkey; Type: FK CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.domains
    ADD CONSTRAINT domains_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES common.domains(id) ON DELETE SET NULL;


--
-- Name: login_history login_history_membership_id_fkey; Type: FK CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.login_history
    ADD CONSTRAINT login_history_membership_id_fkey FOREIGN KEY (membership_id) REFERENCES common.memberships(id) ON DELETE SET NULL;


--
-- Name: login_history login_history_user_id_fkey; Type: FK CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.login_history
    ADD CONSTRAINT login_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES common.users(id) ON DELETE SET NULL;


--
-- Name: memberships memberships_tenant_id_fkey; Type: FK CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.memberships
    ADD CONSTRAINT memberships_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES common.tenants(tenant_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: memberships memberships_user_id_fkey; Type: FK CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.memberships
    ADD CONSTRAINT memberships_user_id_fkey FOREIGN KEY (user_id) REFERENCES common.users(id) ON DELETE CASCADE;


--
-- Name: tenants tenants_domain_id_fkey; Type: FK CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.tenants
    ADD CONSTRAINT tenants_domain_id_fkey FOREIGN KEY (domain_id) REFERENCES common.domains(id) ON DELETE SET NULL;


--
-- Name: coaching_assignment_reasons coaching_assignment_reasons_assignment_id_fkey; Type: FK CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.coaching_assignment_reasons
    ADD CONSTRAINT coaching_assignment_reasons_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES trustguard.coaching_assignments(id) ON DELETE CASCADE;


--
-- Name: coaching_assignment_reasons coaching_assignment_reasons_member_user_id_fkey; Type: FK CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.coaching_assignment_reasons
    ADD CONSTRAINT coaching_assignment_reasons_member_user_id_fkey FOREIGN KEY (member_user_id) REFERENCES common.users(id) ON DELETE CASCADE;


--
-- Name: coaching_assignment_reasons coaching_assignment_reasons_qa_call_id_fkey; Type: FK CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.coaching_assignment_reasons
    ADD CONSTRAINT coaching_assignment_reasons_qa_call_id_fkey FOREIGN KEY (qa_call_id) REFERENCES trustguard.qa_evaluations(call_id) ON DELETE CASCADE;


--
-- Name: coaching_assignments coaching_assignments_assigned_by_user_id_fkey; Type: FK CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.coaching_assignments
    ADD CONSTRAINT coaching_assignments_assigned_by_user_id_fkey FOREIGN KEY (assigned_by_user_id) REFERENCES common.users(id) ON DELETE SET NULL;


--
-- Name: coaching_assignments coaching_assignments_tenant_id_fkey; Type: FK CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.coaching_assignments
    ADD CONSTRAINT coaching_assignments_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES common.tenants(tenant_id) ON UPDATE CASCADE;


--
-- Name: domain_default_eval_items domain_default_eval_items_domain_id_fkey; Type: FK CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.domain_default_eval_items
    ADD CONSTRAINT domain_default_eval_items_domain_id_fkey FOREIGN KEY (domain_id) REFERENCES common.domains(id) ON DELETE CASCADE;


--
-- Name: domain_default_pentagon_axes domain_default_pentagon_axes_domain_id_fkey; Type: FK CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.domain_default_pentagon_axes
    ADD CONSTRAINT domain_default_pentagon_axes_domain_id_fkey FOREIGN KEY (domain_id) REFERENCES common.domains(id) ON DELETE CASCADE;


--
-- Name: eval_item_defs eval_item_defs_tenant_id_fkey; Type: FK CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.eval_item_defs
    ADD CONSTRAINT eval_item_defs_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES common.tenants(tenant_id) ON UPDATE CASCADE;


--
-- Name: ics_qa_poll_watermark ics_qa_poll_watermark_tenant_id_fkey; Type: FK CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.ics_qa_poll_watermark
    ADD CONSTRAINT ics_qa_poll_watermark_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES common.tenants(tenant_id) ON UPDATE CASCADE;


--
-- Name: ksqi_item_defs ksqi_item_defs_tenant_id_fkey; Type: FK CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.ksqi_item_defs
    ADD CONSTRAINT ksqi_item_defs_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES common.tenants(tenant_id) ON UPDATE CASCADE;


--
-- Name: notification_prefs notification_prefs_user_id_fkey; Type: FK CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.notification_prefs
    ADD CONSTRAINT notification_prefs_user_id_fkey FOREIGN KEY (user_id) REFERENCES common.users(id) ON DELETE CASCADE;


--
-- Name: notifications notifications_actor_user_id_fkey; Type: FK CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.notifications
    ADD CONSTRAINT notifications_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES common.users(id) ON DELETE SET NULL;


--
-- Name: notifications notifications_recipient_user_id_fkey; Type: FK CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.notifications
    ADD CONSTRAINT notifications_recipient_user_id_fkey FOREIGN KEY (recipient_user_id) REFERENCES common.users(id) ON DELETE CASCADE;


--
-- Name: notifications notifications_tenant_id_fkey; Type: FK CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.notifications
    ADD CONSTRAINT notifications_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES common.tenants(tenant_id) ON UPDATE CASCADE;


--
-- Name: pentagon_axes pentagon_axes_tenant_id_fkey; Type: FK CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.pentagon_axes
    ADD CONSTRAINT pentagon_axes_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES common.tenants(tenant_id) ON UPDATE CASCADE;


--
-- Name: qa_audit_logs qa_audit_logs_user_id_fkey; Type: FK CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.qa_audit_logs
    ADD CONSTRAINT qa_audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES common.users(id) ON DELETE SET NULL;


--
-- Name: qa_batch_configs qa_batch_configs_tenant_id_fkey; Type: FK CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.qa_batch_configs
    ADD CONSTRAINT qa_batch_configs_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES common.tenants(tenant_id) ON UPDATE CASCADE;


--
-- Name: qa_batch_configs qa_batch_configs_updated_by_fkey; Type: FK CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.qa_batch_configs
    ADD CONSTRAINT qa_batch_configs_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES common.users(id) ON DELETE SET NULL;


--
-- Name: eval_annotation qa_call_annotation_call_id_fkey; Type: FK CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.eval_annotation
    ADD CONSTRAINT qa_call_annotation_call_id_fkey FOREIGN KEY (call_id) REFERENCES trustguard.qa_evaluations(call_id) ON DELETE CASCADE;


--
-- Name: eval_emotion_recovery qa_call_emotion_recovery_call_id_fkey; Type: FK CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.eval_emotion_recovery
    ADD CONSTRAINT qa_call_emotion_recovery_call_id_fkey FOREIGN KEY (call_id) REFERENCES common.calls(call_id) ON DELETE CASCADE;


--
-- Name: eval_item_score qa_call_item_score_call_id_fkey; Type: FK CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.eval_item_score
    ADD CONSTRAINT qa_call_item_score_call_id_fkey FOREIGN KEY (call_id) REFERENCES trustguard.qa_evaluations(call_id) ON DELETE CASCADE;


--
-- Name: eval_ksqi_score qa_call_ksqi_score_call_id_fkey; Type: FK CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.eval_ksqi_score
    ADD CONSTRAINT qa_call_ksqi_score_call_id_fkey FOREIGN KEY (call_id) REFERENCES trustguard.qa_evaluations(call_id) ON DELETE CASCADE;


--
-- Name: eval_ksqi_summary qa_call_ksqi_summary_call_id_fkey; Type: FK CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.eval_ksqi_summary
    ADD CONSTRAINT qa_call_ksqi_summary_call_id_fkey FOREIGN KEY (call_id) REFERENCES trustguard.qa_evaluations(call_id) ON DELETE CASCADE;


--
-- Name: eval_pentagon_result qa_call_pentagon_result_call_id_fkey; Type: FK CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.eval_pentagon_result
    ADD CONSTRAINT qa_call_pentagon_result_call_id_fkey FOREIGN KEY (call_id) REFERENCES trustguard.qa_evaluations(call_id) ON DELETE CASCADE;


--
-- Name: eval_review_event qa_call_review_event_actor_user_id_fkey; Type: FK CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.eval_review_event
    ADD CONSTRAINT qa_call_review_event_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES common.users(id) ON DELETE SET NULL;


--
-- Name: eval_review_event qa_call_review_event_call_id_fkey; Type: FK CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.eval_review_event
    ADD CONSTRAINT qa_call_review_event_call_id_fkey FOREIGN KEY (call_id) REFERENCES trustguard.qa_evaluations(call_id) ON DELETE CASCADE;


--
-- Name: qa_evaluations qa_calls_approved_by_user_id_fkey; Type: FK CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.qa_evaluations
    ADD CONSTRAINT qa_calls_approved_by_user_id_fkey FOREIGN KEY (approved_by_user_id) REFERENCES common.users(id) ON DELETE SET NULL;


--
-- Name: qa_evaluations qa_calls_call_id_fkey; Type: FK CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.qa_evaluations
    ADD CONSTRAINT qa_calls_call_id_fkey FOREIGN KEY (call_id) REFERENCES common.calls(call_id) ON DELETE CASCADE;


--
-- Name: qa_evaluations qa_calls_user_id_fkey; Type: FK CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.qa_evaluations
    ADD CONSTRAINT qa_calls_user_id_fkey FOREIGN KEY (user_id) REFERENCES common.users(id) ON DELETE SET NULL;


--
-- Name: qa_confidence_prompt qa_confidence_prompt_tenant_id_fkey; Type: FK CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.qa_confidence_prompt
    ADD CONSTRAINT qa_confidence_prompt_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES common.tenants(tenant_id) ON UPDATE CASCADE;


--
-- Name: qa_confidence_prompt qa_confidence_prompt_updated_by_fkey; Type: FK CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.qa_confidence_prompt
    ADD CONSTRAINT qa_confidence_prompt_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES common.users(id) ON DELETE SET NULL;


--
-- Name: qa_golden_set qa_golden_set_qa_id_fkey; Type: FK CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.qa_golden_set
    ADD CONSTRAINT qa_golden_set_qa_id_fkey FOREIGN KEY (qa_id) REFERENCES trustguard.qa_evaluations(call_id) ON DELETE CASCADE;


--
-- Name: qa_golden_set qa_golden_set_tenant_id_fkey; Type: FK CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.qa_golden_set
    ADD CONSTRAINT qa_golden_set_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES common.tenants(tenant_id) ON UPDATE CASCADE;


--
-- Name: qa_skill_store qa_skill_store_tenant_id_fkey; Type: FK CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.qa_skill_store
    ADD CONSTRAINT qa_skill_store_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES common.tenants(tenant_id) ON UPDATE CASCADE;


--
-- Name: rubric_change_log rubric_change_log_tenant_id_fkey; Type: FK CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.rubric_change_log
    ADD CONSTRAINT rubric_change_log_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES common.tenants(tenant_id) ON UPDATE CASCADE;


--
-- Name: rubric_change_log rubric_change_log_user_id_fkey; Type: FK CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.rubric_change_log
    ADD CONSTRAINT rubric_change_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES common.users(id) ON DELETE SET NULL;


--
-- Name: tenant_rag_config tenant_rag_config_tenant_id_fkey; Type: FK CONSTRAINT; Schema: trustguard; Owner: -
--

ALTER TABLE ONLY trustguard.tenant_rag_config
    ADD CONSTRAINT tenant_rag_config_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES common.tenants(tenant_id) ON UPDATE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict xxAghGk2FBhcFKvCb0EWZy3EBfZKXXPF2t42huV9hN5WHCUV3YYtgRXGgqTgXfm

